
name: "Teste"

on:
  workflow_dispatch:

jobs:
  concat:
    runs-on: windows-latest
    steps:      
      - uses: actions/checkout@v4
      - name: "Print"
        run: |

          $Password = "${{ secrets.TEST_PASSWORD }}"
          $dest = "contentPath=$SiteName,computerName=$authUrl,userName=`"${{ secrets.TEST_USER }}`",password=`"$Password`",authType=Basic"
          Write-Host "DEST = $dest"
